set GLEW_HOME=D:\libs\glew_1_10_0
set GLOBJECTS_HOME=C:\Program Files\globjects
set QT_DIR=C:\Qt\qt-5.2.0\qtbase
set GLM_HOME=D:\libs\glm
set ASSIMP_HOME=D:\libs\assimp_3_0_1270-sdk
set GTEST_HOME=D:/libs/gmock/gmock-1_7_0/gtest
set GMOCK_HOME=D:/libs/gmock/gmock-1_7_0
set LIBZEUG_HOME=C:\Program Files\libzeug
set QT_QPA_PLATFORM_PLUGIN_PATH=%QT_DIR%/plugins/platforms
set WINDOWS_SDK=C:/Program Files (x86)/Windows Kits/8.1/
set CMAKE_PREFIX_PATH=C:/Program Files (x86)/Windows Kits/8.1/Lib/winv6.3/um/x64
set PATH=%WINDOWS_SDK%/bin/x64;%GLEW_HOME%/bin;%ASSIMP_HOME%/bin/x64;%QT_DIR%/bin;%PATH%;%LIBZEUG_HOME%;%LIBZEUG_HOME%/build/Debug;%LIBZEUG_HOME%/build/Release